<script>
</script>

<div class="max-w-3xl mx-auto px-6 py-16">
	<a href="/" class="text-gray-500 hover:text-gray-900 text-sm mb-8 inline-block">&larr; Back to Domain AI Agent</a>

	<h1 class="text-3xl font-semibold text-gray-900 tracking-tight mb-8">Privacy & Terms</h1>

	<div class="prose prose-gray max-w-none">
		<h2>Privacy Policy</h2>
		<p>Domain AI Agent is built by AutoBirds. We respect your privacy and are committed to protecting your data.</p>

		<h3>What we collect</h3>
		<ul>
			<li><strong>Search descriptions</strong> - Used to generate domain suggestions</li>
			<li><strong>Preferences</strong> - Liked/disliked domains to improve suggestions</li>
			<li><strong>Email</strong> - Only if you subscribe for updates</li>
		</ul>

		<h3>What we don't do</h3>
		<ul>
			<li>We don't sell your data</li>
			<li>We don't share your searches with third parties</li>
			<li>We don't track you across other websites</li>
		</ul>

		<h3>Data storage</h3>
		<p>Your preferences are stored locally in your browser and optionally synced to our servers to persist across devices.</p>

		<h2>Terms of Service</h2>
		<p>By using Domain AI Agent, you agree to:</p>
		<ul>
			<li>Use the service for lawful purposes only</li>
			<li>Not abuse the API or attempt to overload our servers</li>
			<li>Understand that domain availability information may not be 100% accurate</li>
		</ul>

		<h3>Disclaimer</h3>
		<p>Domain suggestions are generated by AI and availability is checked via RDAP. We cannot guarantee that suggested domains are available for registration or that prices are accurate. Always verify with your preferred registrar before purchasing.</p>

		<h2>Contact</h2>
		<p>Questions? Reach us at <a href="mailto:hello@autobirds.com">hello@autobirds.com</a></p>
	</div>

	<div class="mt-12 pt-8 border-t border-gray-200 text-center text-xs text-gray-500">
		<p>Made by <a href="https://autobirds.com" target="_blank" class="font-semibold text-gray-900 hover:underline">AutoBirds</a></p>
	</div>
</div>
