import { json } from '@sveltejs/kit';
import type { RequestHandler } from './$types';

export const POST: RequestHandler = async ({ request, platform }) => {
	try {
		const body = await request.json();
		const { email, domains } = body;

		if (!email || !email.includes('@')) {
			return json({ error: 'Valid email is required' }, { status: 400 });
		}

		if (!domains || domains.length === 0) {
			return json({ error: 'No domains to send' }, { status: 400 });
		}

		const resendKey = (platform?.env as Record<string, string>)?.RESEND_API_KEY;
		if (!resendKey) {
			return json({ error: 'Email service not configured' }, { status: 500 });
		}

		// Build domain list HTML
		const domainListHtml = domains
			.map((d: string) => `<li style="margin: 8px 0;"><strong>${d}</strong> - <a href="https://www.namecheap.com/domains/registration/results/?domain=${encodeURIComponent(d)}">Check availability</a></li>`)
			.join('');

		// Send email
		const { Resend } = await import('resend');
		const resend = new Resend(resendKey);
		await resend.emails.send({
			from: 'Domain AI Agent <hello@autobirds.com>',
			to: email,
			subject: `Your ${domains.length} Liked Domain${domains.length > 1 ? 's' : ''}`,
			html: `
				<h1>Your Liked Domains</h1>
				<p>Here are the domain names you liked:</p>
				<ul style="list-style: none; padding: 0;">
					${domainListHtml}
				</ul>
				<hr style="margin: 20px 0; border: none; border-top: 1px solid #eee;">
				<p style="color: #666; font-size: 14px;">
					Generated by <a href="https://domains.autobirds.com">Domain AI Agent</a>
				</p>
			`
		});

		return json({ success: true });
	} catch (error) {
		console.error('Send liked error:', error);
		return json({ error: 'Failed to send email' }, { status: 500 });
	}
};
